# Generated by Django 4.1.1 on 2022-09-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dishes', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=5)),
                ('Food_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.food_classification')),
            ],
        ),
    ]
