# Generated by Django 4.1.1 on 2022-09-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name_of_dishes',
            field=models.CharField(max_length=40),
        ),
    ]
